# Generated by Django 2.0.3 on 2018-03-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='compania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnc', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('num_fac', models.IntegerField()),
                ('pref_ncf', models.CharField(max_length=30)),
                ('sec_ncf', models.IntegerField()),
                ('comprobante', models.CharField(max_length=2)),
                ('num_max_comp', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
